# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUVhvefRI7ZpKu0RPL4pK8djTBVcD2w4
"""

import numpy as np
import matplotlib.pyplot as plt
# 平均 40, 標準偏差 15 の正規乱数を1,000件⽣成
x = np.random.normal(40, 15, 1000)
# ヒストグラムを出⼒
plt.hist(x, bins=16,rwidth=0.8)

import numpy as np
import matplotlib.pyplot as plt

#データ準備
dataset1=np.random.normal(45, 12, 200) # (1)データの格納(男性)
dataset2=np.random.normal(38, 8, 200) # (2)データの格納(⼥性)

#グラフの描画
plt.hist(dataset1, alpha=0.5, bins=20, label="Man") # (3) ヒストグラムの描画(男性)
plt.hist(dataset2, alpha=0.3, bins=20, label="Woman", color='r') # (4) ヒストグラムの描画(⼥性)

plt.legend(loc="upper left", fontsize=15) # (5)凡例表⽰

import matplotlib.pyplot as plt
import pandas as pd #Pandasのインポート

#データ準備
sales1=pd.read_csv("date/Sales_Area_A.csv",squeeze=True)#csvファイルの読み込み
sales2= pd.read_csv("date/Sales_Area_B.csv", squeeze = True) #csvファイルの読み込み

#グラフの装飾
plt.xlim(350, 1300) # x軸の表⽰範囲
plt.ylim(0, 100) # y軸の表⽰範囲
plt.title("Purchase Frequency", fontsize=20) #タイトル
plt.xlabel("Price", fontsize=20) #x軸ラベル
plt.ylabel("Frequency", fontsize=20) # y軸ラベル
plt.grid(True) # ⽬盛線の表⽰
plt.tick_params(labelsize = 12) # ⽬盛線のラベルサイズ

# グラフの描画
plt.hist(sales1) #ヒストグラムの描画
plt.hist(sales2)

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd/content/gdrive/MyDrive/信号理論